server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/UniversityDB
    username: University
    password: 1

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-request-size: 100000MB
      max-file-size: 100000MB

upload:
  server:
    folder: root/ProjectFiles


