server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/UniversityDB
    username: University
    password: 1

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 10MB

upload:
  server:
    folder: C:/Users/User/OneDrive/Documents/upload
